### ISSUE TITLE
Nice README

### ISSUE THREAD

**Issue by matthewdking** [FACN3/GHM-Portfolio#26]
### AWESOME :tada: 

I really like that you've added a section about the updates and the technologies in use :+1:. You mention the user stories but it could be a good idea to include the ones mentioned [here](https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-1/project.md).

**Comment by matthewdking** [comment]
@MynahMarie please don't close issues that I raise.

**Comment by MynahMarie** [comment]
@matthewdking Ok sorry! I added the link to the readme so I thought I could close...
