### ISSUE TITLE
Link to the website?

### ISSUE THREAD

**Issue by matthewdking** [FACN3/GHM-Portfolio#32]
For this project it's a really good idea to host the site using github pages and provide a link in the README so people can view your site.

**Comment by matthewdking** [comment]
@MynahMarie please don't close issue that you haven't created. Please try to solve the issue I have raised and then assign me and I can close it. Thanks :smile:

**Comment by MynahMarie** [comment]
@matthewdking sorry again, learning the workflow... :blush:

**Comment by matthewdking** [comment]
No worries, thanks for adding the link :+1: remember next time to relate a commit and pull request to the issue you are working on as well :innocent:
